### ISSUE TITLE
`Operation is not supported on this platform` Exception in Blazor

### ISSUE THREAD

**Issue by alensiljak** [StefH/WebDAV-Client#14]
Trying an extremely simple example in Blazor:

```
using var client = new WebDav.WebDavClient();
var result = await client.Propfind("/");
```
results in an exception:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.BrowserHttpHandler.set_Credentials(ICredentials value)
   at System.Net.Http.HttpClientHandler.set_UseDefaultCredentials(Boolean value)
   at WebDav.WebDavClient.ConfigureHttpClient(WebDavClientParams params)
   at WebDav.WebDavClient..ctor(WebDavClientParams params)
   at WebDav.WebDavClient..ctor()
   at Cashier.Components.Pages.WebDAVDemo.OnClientLs() in D:\src\cashier-blazor\src\Cashier\Components\Pages\WebDAVDemo.razor:line 54
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by alensiljak** [comment]
Aha, this is due to the default HttpClient. 
It is necessary to pass the injected HttpClient from a Blazor page.

**Comment by StefH** [comment]
See also the Blazor example apps here:
https://github.com/StefH/WebDAV-AudioPlayer/tree/master/src

**Comment by StefH** [comment]
https://github.com/StefH/WebDAV-Client/issues/13

**Comment by alensiljak** [comment]
I need to find a way to link to the local sources instead of a NuGet package and will then gladly debug through.

**Comment by StefH** [comment]
> I need to find a way to link to the local sources instead of a NuGet package and will then gladly debug through.

Just download this whole repository as a zip, unzip it to a location, and include the project in your solution, and link to this project instead of the nuget.

**Comment by alensiljak** [comment]
ok, this is now sorted but problems seem to never end :D
