### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by alensiljak** [StefH/WebDAV-Client#15]
Following up on the simple test:
```
httpClient.BaseAddress = new Uri("http://localhost:8080/");
using var client = new WebDav.WebDavClient(httpClient);
var result = await client.Propfind("/");
```
results in a CORS exception:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: NetworkError when attempting to fetch resource.
System.Net.Http.HttpRequestException: TypeError: NetworkError when attempting to fetch resource.
 ---> TypeError: NetworkError when attempting to fetch resource.
   --- End of inner exception stack trace ---
   at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|53_0(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebDav.Infrastructure.WebDavDispatcher.Send(Uri requestUri, HttpMethod method, RequestParameters requestParams, CancellationToken cancellationToken)
   at WebDav.WebDavClient.Propfind(Uri requestUri, PropfindParameters parameters)
   at Cashier.Components.Pages.WebDAVDemo.OnClientLs() in D:\src\cashier-blazor\src\Cashier\Components\Pages\WebDAVDemo.razor:line 56
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

However, CORS access is enabled. I'm using rclone with `--allow-origin "*"` and can confirm that issuing OPTIONS and PROPFIND HTTP commands works with the same HttpClient.

Also, if I try to mix using the HttpClient directly and then using the WebDAV client to which the HttpClient has been passed in the constructor, it throws a different exception.

**Comment by StefH** [comment]
I think/know that accessing a connection directly from the Blazor WebAssembly frontend is not possible/blocked.

A work-around for this is to build a static webapp in which the API (running in Azure Function) can access the connection.

For another example for this, see:
- https://github.com/StefH/Blazor.YouTubeDownloader

**Comment by alensiljak** [comment]
> I think/know that accessing a connection directly from the Blazor WebAssembly frontend is not possible/blocked.

That's not entirely true. As I've mentioned, I'm successfully issuing WebDAV/HTTP requests using the HttpClient directly. I can get the response for both OPTIONS and PROPFIND

![image](https://github.com/StefH/WebDAV-Client/assets/462445/f483fbb8-b187-4ab8-92e9-eb20bf5a5954)

The issue happens, however, when going through the WebDAV Client. I haven't looked deeply into the code yet but thought you may have an idea of why this would be the case.

My sample code is at https://github.com/alensiljak/cashier-blazor, WebDAVDemo.razor page. The server is rclone 1.65 (which supports most WebDAV methods).

**Comment by alensiljak** [comment]
This is a bit weird. If I add a simple line to
https://github.com/StefH/WebDAV-Client/blob/b67ff76f62df27a7fef2fb1151d54dc74a686048/src/WebDAV-Client/Infrastructure/WebDavDispatcher.cs#L39

```cs
var response1 = await _httpClient.SendAsync(request);
```
which, btw, works in the Blazor page, is using the same HttpClient injected into the page, and can actually issue PROPFIND on its own,
I still get an exception on that line, when the request is issued.

My suspicion is still that the references to HttpClient in a regular .Net library are using something that is not present in the (stripped-down?) HttpClient provided in the browser.

**Comment by alensiljak** [comment]
Ah, right. It seems that the HttpClient available in Blazor sends HttpRequestMessage, not HttpRequest. It also returns HttpResponseMessage, not HttpResponse.

**Comment by alensiljak** [comment]
The problem seems to manifest itself because the Depth:1 header is added to the request.
This made me check the server and, correctly, it is a problem with rclone's webdav implementation. Now I'll focus on resolving that - https://github.com/rclone/rclone/issues/7492.
Seems that the client is correct, after all. I've tested it with dufs and it correctly lists only the current folder. Fantastic.

The difference to the manually issued PROPFIND was that I was not setting any headers.
